services:
  web:
    build: .
    ports:
      - 3000
    deploy:
      replicas: 1
    depends_on:
      - postgres
    networks:
      - app_net

  nginx:
    image: nginx:latest
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 443:443
      - 80:80
    depends_on:
      - web
    networks:
      - app_net

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD={$POSTGRES_PASSWORD}
      - POSTGRES_USER={$POSTGRES_USER}
      - POSTGRES_DB={$POSTGRES_DB}
    networks:
      - app_net

networks:
  app_net: