services:
  frontend:
    image: diametrfq/website:latest
    container_name: website_frontend
    environment:
      - RUST_BACKEND_URL=http://backend:8080
    networks:
      - app_network
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    image: diametrfq/website-backend:latest
    container_name: website_backend
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REFRESH_TOKEN=${SPOTIFY_REFRESH_TOKEN}
    networks:
      - app_network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: website_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./configs/deploy/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app_network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: prometheus
    volumes:
      -  ./configs/logging/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention.time=15d'
    networks:
      - app_network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.1.5
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./configs/logging/grafana-provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=https://diametrfq.ru/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    networks:
      - app_network
    restart: unless-stopped
    depends_on:
      - loki
      - prometheus

  node-exporter:
    image: prom/node-exporter:v1.6.1
    container_name: node_exporter
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - app_network
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - app_network
    command:
      - '--store_container_labels=false'
      - '--docker_only'
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    volumes:
      - ./configs/logging/loki/loki-config.yaml:/etc/loki/local-config.yaml:ro
      - loki-storage:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - app_network

  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail
    user: root
    volumes:
      - ./configs/logging/promtail/promtail-config.yaml:/etc/promtail/config.yaml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - app_network
    depends_on:
      - loki

volumes:
  prometheus_data:
  grafana_data:
  loki-storage:

networks:
  app_network:
    driver: bridge