version: '3.8'

services:
  frontend:
    image: diametrfq/website:latest
    container_name: website_frontend
    ports:
      - "3000"
    environment:
      - RUST_BACKEND_URL=http://website-backend:8080/
    networks:
      - app_network
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    image: diametrfq/website-backend:latest
    container_name: website_backend
    ports:
      - "8080"
    environment:
      - RUST_LOG=${RUST_LOG_LEVEL:-debug}
    networks:
      - app_network
    restart: unless-stopped

  nginx:
    image: nginx:latest 
    container_name: website_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf.prod:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro 
      - /var/www/certbot:/var/www/certbot:ro 
    depends_on:
      - frontend
      - backend
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
