services:
  web:
    image: diametrfq/fast-app-prometheus-web
    ports:
      - "5000:5000"
    networks:
      - fast-app-prometheus
    deploy:
      replicas: 4
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  prometheus:
    image: prom/prometheus
    networks:
      - fast-app-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.ymld

  grafana:
    image: grafana/grafana
    networks:
      - fast-app-prometheus
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  elasticsearch:
    image: elasticsearch:7.9.3
    networks:
      - fast-app-prometheus
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  logstash:
    image: logstash:7.9.3
    networks:
      - fast-app-prometheus
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5010:5010"

  kibana:
    image: kibana:7.9.3
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  esdata:

networks:
  fast-app-prometheus:
    external: true