import TelegramPosts from '@/app/[locale]/telegram/components/TelegramPosts';
import { Metadata } from 'next';
import "./styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Home: React.FC = () => {
  return (
    <div style={{ maxWidth: '800px', margin: '0 auto', padding: '20px'}}>
      <TelegramPosts />
    </div>
  );
};

export default Home;