version: '3'

services:
  web:
    build: .
    ports:
      - "80:5000"
      - "443`:5000"
    networks:
      - app_net

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - app_net


  certbot:
    image: certbot/certbot
    volumes:
    - /etc/letsencrypt:/etc/letsencrypt
    - /var/www/certbot:/var/www/certbot

networks:
  app_net: