version: '3'

services:
  web:
    build: .
    ports:
      - "80:5000"
      - "443`:5000"
    deploy:
      replicas: 3 # Запускаем 3 экземпляра Flask-приложения
    networks:
      - app_net
  nginx:
    image: nginx:latest # Используем образ Nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Подключаем локальный файл конфигурации Nginx
    ports:
      - "80:80" # Пробрасываем порт 80 для внешнего доступа
    depends_on:
      - web # Nginx зависит от Flask-приложения
    networks:
      - app_net

networks:
  app_net: